package com.rnmedia3playerdemo

import com.facebook.react.bridge.ReadableMap
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.uimanager.SimpleViewManager
import com.facebook.react.uimanager.ThemedReactContext
import com.facebook.react.uimanager.ViewManagerDelegate
import com.facebook.react.uimanager.annotations.ReactProp
import com.facebook.react.viewmanagers.Media3PlayerViewManagerDelegate
import com.facebook.react.viewmanagers.Media3PlayerViewManagerInterface

/**
 * ViewManager for the custom Media3PlayerView.
 * Responsible for creating the view, handling props from JS, and managing events.
 */
@ReactModule(name = Media3PlayerViewManager.NAME)
class Media3PlayerViewManager :
    SimpleViewManager<Media3PlayerView>(),
    Media3PlayerViewManagerInterface<Media3PlayerView> {

    companion object {
        // The name used to reference this view manager from JS
        const val NAME = "Media3PlayerView"
    }

    // Delegate handles communication and prop mapping automatically when generated by Codegen
    private val delegate = Media3PlayerViewManagerDelegate(this)

    /**
     * Returns the delegate instance for prop/event mapping.
     */
    override fun getDelegate(): ViewManagerDelegate<Media3PlayerView> = delegate

    /**
     * Returns the unique name for this ViewManager, used by React Native.
     */
    override fun getName(): String = NAME

    /**
     * Creates and returns a new Media3PlayerView instance for this ViewManager.
     * @param reactContext ThemedReactContext provided by React Native
     */
    override fun createViewInstance(reactContext: ThemedReactContext): Media3PlayerView {
        return Media3PlayerView(reactContext)
    }

    /**
     * Handles the "source" prop for Media3PlayerView.
     * Extracts the "uri", optional DRM license URL, and headers from the ReadableMap and forwards
     * them to the view for loading the media source and DRM configuration.
     */
    @ReactProp(name = "source")
    override fun setSource(view: Media3PlayerView, source: ReadableMap?) {
        val uri = source?.getString("uri")
        val type = source?.getString("type")
        var licenseUrl: String? = null
        var headers: Map<String, String>? = null
        val drmMap = source?.getMap("drm")

        if (drmMap != null) {
            licenseUrl = drmMap.getString("licenseUrl")
            val headersArray = drmMap.getArray("headers")
            if (headersArray != null) {
                val map = mutableMapOf<String, String>()
                for (i in 0 until headersArray.size()) {
                    val entry = headersArray.getMap(i)
                    val key = entry?.getString("key")
                    val value = entry?.getString("value")
                    if (key != null && value != null) {
                        map[key] = value
                    }
                }
                headers = map
            }
        }
        if (!uri.isNullOrEmpty()) {
            view.setSource(uri, type, licenseUrl, headers)
        }
    }

    /**
     * Sets the "autoplay" property on the Media3PlayerView.
     * Controls whether playback should start automatically when ready.
     */
    @ReactProp(name = "autoplay", defaultBoolean = false)
    override fun setAutoplay(view: Media3PlayerView, value: Boolean) {
        view.setAutoplay(value)
    }

    /**
     * Sets the "play" property on the Media3PlayerView.
     * Controls whether the player should be playing or paused.
     */
    @ReactProp(name = "play", defaultBoolean = false)
    override fun setPlay(view: Media3PlayerView, value: Boolean) {
        view.setPlay(value)
    }

    /**
     * Sets the "mute" property on the Media3PlayerView.
     * Controls whether the audio should be muted.
     */
    @ReactProp(name = "mute", defaultBoolean = false)
    override fun setMute(view: Media3PlayerView, value: Boolean) {
        view.setMute(value)
    }

    /**
     * Called when the React Native view instance is about to be dropped/remounted.
     * Ensures resources are released to avoid leaks.
     */
    override fun onDropViewInstance(view: Media3PlayerView) {
        super.onDropViewInstance(view)
        view.releasePlayer()
    }

    /**
     * Exports native direct event types to React Native for event binding in JS.
     * Maps native event names to the registration name expected by React.
     */
    override fun getExportedCustomDirectEventTypeConstants(): MutableMap<String, Any> {
        return mutableMapOf(
            "topReady" to mapOf("registrationName" to "onReady"),
            "topEnd" to mapOf("registrationName" to "onEnd"),
            "topError" to mapOf("registrationName" to "onError")
        )
    }
}
